	 #include<conio.h>
	 #include<stdio.h>
	 #include<string.h>
	 void main()
	 {clrscr();
	 char c[8]="anjali",copy_arr[8][8],c1[8];
	 char d[8]="kumari";
	/* int l1=strlen(c);
       //	 printf("%d",l1);
	 char a=d[1];
	 int range;
	 //int l2=strlen(a);
	// printf("%d",l2);
	if(strlen(c)>strlen(d)){ range=strlen(c);
	    }
	else {range=strlen(d);
      //	str
		}
	for(int i=1; i<=range;i++)  {
//	while
int j=1;
	 strncpy(c1,c+1,2-1);
     //	 printf("%s\n",c1);
//     copy_arr[i][j]= { c1[i]};      */
     printf("%p",&c);

			// }
	   getch();
	 }