#include<stdio.h>
#include<conio.h>
#include<math.h>

int main()
{
















printf("\n\n-------------------------question no-14-----------------------\n\n");
printf("\nsolution for the series:\n---------------\ns = x - 1/3+1/5.....\n----------------\n");
printf("\nenter the value of x");
scanf("%d",&x);
printf("enter how many terms");
scanf("%d",&n);

printf("\n\n-------------------------question no-15------------------------\n\n");
printf("\nsolution for the series:\n---------------\ns = x - x^3 + x^5 - x^7......x^n\n----------------\n");
printf("\nenter the value of x");
scanf("%d",&x);
printf("how many terms?");
scanf("%d",&n);

printf("\n\n-------------------------question no-16------------------------\n\n");
printf("\nsolution for the series:\n---------------\ns = x - x^3 + x^5 - x^7......x^n\n----------------\n");
printf("\nenter the value of x");
scanf("%d",&x);
printf("how many terms");
scanf("%d",&n);

printf("\n\n-------------------------question no-17-------------------------\n\n");
printf("\nsolution for the series:\n---------------\ns = x - x^3 + x^5 - x^7......x^n\n----------------\n");
printf("\nenter the value of x");
scanf("%d",&x);
printf("how many terms");
scanf("%d",&n);

printf("\n\n-------------------------question no-18-------------------------\n\n");
printf("\nsolution for the series:\n---------------\ns = x - x^3 + x^5 - x^7......x^n\n----------------\n");
printf("\nenter the value of x");
scanf("%d",&x);
printf("how many terms?");
scanf("%d",&n);

printf("\n\n-------------------------question no-19------------------------\n\n");
printf("how many terms?");
scanf("%d",&n);



 getch();
 }
